spring.application.name=bloodbank-backend
 
# Database Configuration - update credentials as needed


#spring.datasource.url=jdbc:mysql://localhost:3306/bloodbank_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://mysql-30077f24-cognizant-7a9.h.aivencloud.com:20072/defaultdb?sslMode=VERIFY_CA&trustCertificateKeyStoreUrl=classpath:ca.pem&trustCertificateKeyStoreType=PEM
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
 
# JWT Configuration
app.jwt.secret=bloodBankSecretKey2024!BloodBankSecretKey2024!BloodBankSecretKey2024!
app.jwt.expiration=86400000
 
# Mail Configuration (Gmail SMTP) - update with your credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ujmishra01@gmail.com
spring.mail.password=zxdc flio otno fkrt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=ujmishra01@gmail.com
app.frontend.url=http://localhost:4200
 
# Server
server.port=7777
logging.level.com.bloodbank=INFO
 
# Test Data — set to true ONCE to seed sample users/requests/donations, then back to false
app.seed-test-data=false